import Sidemenu from "../sideMenu/sideMenu";
import Head from "next/head";
import Box from "../box/Box";
import Leftcontent from "../leftContent/leftContent";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.scss";

const Layout = ({ children }) => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Student Management Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="student-wrapper">
        <Box classes={"h-full  min-h-[92vh]"}>
          <div
            className={
              router.pathname != "/allstudents"
                ? styles.studentMain
                : styles.studentMain_col
            }
          >
            <div className="side-menu">
              <Sidemenu />
            </div>
            <div className="main-content">{children}</div>
            {router.pathname != "/allstudents" && <Leftcontent />}
          </div>
        </Box>
      </div>
    </div>
  );
};

export default Layout;
